CompileFlags:
    Add:
        - -xc++
        - -Wall
        - -I/usr/include/c++/11
        - -I/usr/include/x86_64-linux-gnu/c++/11
        - -I/home/wanghuacheng/opt/ac/include
    Remove: -W*
    Compiler: g++

Diagnostics:
  UnusedIncludes: Strict
